format_version: 10
pipelines:
  backend-tmp:
    group: App-Deployments
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-a66247d:
        git: https://github.com/cDevOps78/expenseAnsibleGoCD.git
        shallow_clone: true
        auto_update: true
        branch: main
    environment_variables:
      component: backend
    template: ansible-templates

#