format_version: 10
pipelines:
  backend:
    group: Expense-Ansible
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-214f6fa:
        git: https://github.com/ActionsRoboshop/expense-ansible.git
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
      - DEV:
          environment_variables:
            env: dev
            component: backend
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: false
          approval:
            type: manual
            allow_only_on_success: false
          jobs:
            job1:
              timeout: 0
              tasks:
                - exec: {arguments: [-i,'backend-dev.azcart.online,',-e,"env=$env",-e,"component=$component",-e,ansible_user=ec2-user,-e,ansible_password=DevOps321,role-call.yml],command: ansible-playbook, run_if: passed}
