format_version: 10
pipelines:
  servers-create:
    group: Expense-Ansible
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    environment_variables:
      server_name: ""
    materials:
      git-214f6fa:
        git: https://github.com/ActionsRoboshop/expense-ansible.git
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
      - DEV:
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: false
          approval:
            type: manual
            allow_only_on_success: false
          jobs:
            job1:
              timeout: 0
              tasks:
                - exec:
                    arguments:
                      - create-servers.sh
                    command: bash
                    run_if: passed
